name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.8
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  geolocator: ^14.0.2
  get_it: ^9.2.0
  google_nav_bar: ^5.0.7
  http: ^1.6.0
  internet_connection_checker: ^3.0.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
